Wallet.UCSService/Models/CreateQrInvoiceRequest.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Wallet.UCSService.Models
{
    public class CreateQrInvoiceRequest
    {
        public string QRId { get; set; }
    }
}

Wallet.UCSService/Models/GetQrInfoRequest.cs
namespace Wallet.UCSService.Models
{
    public class GetQrInfoRequest
    {
        public string TerminalId { get; set; }
        public string QRId { get; set; }
    }
}

Wallet.UCSService/Models/UcsDemoModel.cs
using Wallet.UCSService.Core.Obj;

namespace Wallet.UCSService.Models
{
    public class UcsDemoModel
    {
        public UcsOrder Order { get; set; }

        public string Action { get; set; }
    }
}

Wallet.UCSService/Models/W1InvoiseNotificationModel.cs
namespace Wallet.UCSService.Models
{
    public class W1InvoiseNotificationModel
    {
        public string WMI_MERCHANT_ID { get; set; }
        public string WMI_PAYMENT_AMOUNT { get; set; }
        public string WMI_CURRENCY_ID { get; set; }
        public string WMI_PAYMENT_NO { get; set; }
        public string WMI_ORDER_ID { get; set; }
        public string WMI_ORDER_STATE { get; set; }
        public string WMI_SIGNATURE { get; set; }
    }
}

Wallet.UCSService/Controllers/UcsApiController.cs
using System;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Web.Http;
using System.Web.Mvc;
using Newtonsoft.Json;
using Wallet.UCSService.Core;
using Wallet.UCSService.Core.Interfaces;
using Wallet.UCSService.Core.Stubs;
using Wallet.UCSService.Models;
using System.Net.Http.Headers;
using Wallet.UCSService.Core.Obj;

namespace Wallet.UCSService.Controllers
{
    public class UcsApiController : ApiController
    {
        protected IInvoicingService InvoicingService;
        protected IStorage Storage;
        protected IUCSService UcsService;


        public UcsApiController()
        {
            var stub = UCSStub.Instance;
            
            InvoicingService = stub;
            Storage = stub;
            UcsService = stub;

        }

        [System.Web.Http.HttpPost]
        [System.Web.Http.HttpGet]
        public HttpResponseMessage GetQrInfo(GetQrInfoRequest request)
        {
            if (request == null)
                return CreateResponse(new UcsOrder {OrderState = UcsOrder.OrderState_Error}, HttpStatusCode.NotFound);

            var merch = Storage.ResolveMerchant(request.TerminalId);
            //validate request here

            var order = Storage.GetOrder(request.QRId);
            if (order == null)
            {
                order = new UcsOrder
                    {
                        OrderState = UcsOrder.OrderState_InfoRequested, 
                        QrId = request.QRId,
                        MerchantId = "119973638979",
                        MerchantName = "Walletone",
                        MerchantLogoUrl = @"http://www.w1.ru/static/upload/8c38f29eb0e14418867af8af0036e5ce.png"
                    };
                Storage.StoreOrder(order);
                UcsService.RequestOrderInfo(request.QRId);
            }
            
            return CreateResponse(order);
        }


        [System.Web.Http.HttpPost]
        [System.Web.Http.HttpGet]
        public HttpResponseMessage CreateQrInvoice(CreateQrInvoiceRequest request)
        {
            if (request == null)
                return CreateResponse(new Invoice() { InvoiceStateId = "error"}, HttpStatusCode.NotFound);

            var terminalId = "";//get from qr

            var merch = Storage.ResolveMerchant(terminalId);
            //validate request here

            var order = Storage.GetOrder(request.QRId);
            if (order == null)
                return CreateResponse(new Invoice() { InvoiceStateId = "error" }, HttpStatusCode.NotFound);

            var invoice = InvoicingService.CreateInvoiceByQr(order, merch);
            
            return CreateResponse(invoice);
        }


        [System.Web.Http.HttpPost]
        public HttpResponseMessage InvoiceState([FromBody]W1InvoiseNotificationModel data)
        {

            var log = new StringBuilder();
            log.AppendFormat("\n\n{0}\n", DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss"));
            
            //if (data != null)
            //{
            //    foreach (var k in data.AllKeys)
            //        log.AppendFormat("{0} = {1}\n", k, data[k]);
            //}

            if (data != null)
            {
                log.AppendFormat("WMI_ORDER_ID = {0}\n", data.WMI_ORDER_ID);
                log.AppendFormat("WMI_MERCHANT_ID = {0}\n", data.WMI_MERCHANT_ID);
                log.AppendFormat("WMI_PAYMENT_NO = {0}\n", data.WMI_PAYMENT_NO);
                log.AppendFormat("WMI_ORDER_STATE = {0}\n", data.WMI_ORDER_STATE);

                var order = Storage.GetOrder(data.WMI_PAYMENT_NO);
                if (order != null)
                {
                    order.OrderState = UcsOrder.OrderState_Ok;
                    Storage.StoreOrder(order);
                }
            }

            File.AppendAllText(@"c:\kill\log\out.txt", log.ToString());

            

            return new HttpResponseMessage(HttpStatusCode.OK) {Content = new StringContent("WMI_RESULT=OK", Encoding.UTF8)};
            //return CreateResponse(null);
        }


        protected HttpResponseMessage CreateResponse(object responseObj, HttpStatusCode code = HttpStatusCode.OK)
        {
            var response = new HttpResponseMessage(code);
            string content = string.Empty;
            
            if (responseObj != null)
                content = JsonConvert.SerializeObject(responseObj, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore });
            
            response.Content = new StringContent(content);
            response.Content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            return response;
        }
    }
}

Wallet.UCSService/Controllers/UcsDemoController.cs
using System.Web.Mvc;
using Wallet.UCSService.Core.Obj;
using Wallet.UCSService.Core.Stubs;
using Wallet.UCSService.Models;

namespace Wallet.UCSService.Controllers
{
    public class UcsDemoController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            var model = new UcsDemoModel();
            model.Order = UCSStub.Instance.CurrentOrder;
            return View(model);
        }

        [HttpPost]
        public ActionResult Index(UcsDemoModel model)
        {
            if (model != null && model.Order != null)
            {
                switch (model.Action)
                {
                    case "refresh":
                        model.Order = UCSStub.Instance.CurrentOrder;
                        break;


                    case "update":
                        var tmp = UCSStub.Instance.CurrentOrder;
                        tmp.Items = model.Order.Items;
                        UCSStub.Instance.CurrentOrder = tmp;
                        break;


                    case "make_paid":
                        //????
                        break;

                    case "make_err":
                        model.Order.OrderState = UcsOrder.OrderState_Error;
                        model.Order.ErrorDescription = "Error text is here";
                        UCSStub.Instance.CurrentOrder = model.Order;
                        break;
                }
            }

            return View(model);
        }

    }
}

Wallet.UCSService/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

Wallet.UCSService/Views/UcsDemo/Index.cshtml
@using Wallet.UCSService.Core.Obj
@model Wallet.UCSService.Models.UcsDemoModel


@using(Html.BeginForm("index", "UcsDemo", FormMethod.Post))
{
    if (Model.Order != null && Model.Order.Items != null)
    {
        @Html.Hidden("Order_OrderState", Model.Order.OrderState)
        @Html.Hidden("Order_ErrorDescription", Model.Order.ErrorDescription)
        
        <p>QR id: @Model.Order.QrId</p><br/>
        <p>Orer state: @Model.Order.OrderState</p><br/>
    
        if (!string.IsNullOrEmpty(Model.Order.ErrorDescription))
        {
            <p>Error description: @Model.Order.ErrorDescription</p><br/>
        }
        
        for (int i = 0; i < 5; i++)
        {
            if (Model.Order.Items.Count <= i)
            {
                Model.Order.Items.Add(new UcsOrderItem());
            }

            @Html.Label("Name")
            @Html.TextBoxFor(model => model.Order.Items[i].Name)

            @Html.Label("Quantity")
            @Html.TextBoxFor(model => model.Order.Items[i].Quantity)

            @Html.Label("Price")
            @Html.TextBoxFor(model => model.Order.Items[i].Price)

            <br />
            <br />
        }
        
        <br />
        <br />
        <input type="submit" name="Action" value="refresh" />
    
        <br />
        <br />
        <input type="submit" name="Action" value="update"/>
    @*
        <br />
        <br />
        <input type="submit" name="Action" value="make_paid"/>
    
        <br />
        <br />
        <input type="submit" name="Action" value="make_err"/>
    *@
    }
}